# Generated by Django 5.1.4 on 2025-01-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0028_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundraise",
            name="total_nfts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total number of NFTs to be distributed for this fundraise",
            ),
        ),
    ]
