# Generated by Django 5.1.5 on 2025-01-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0029_fundraise_total_nfts"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundraise",
            name="has_nft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fundraise",
            name="min_rsc_for_nft",
            field=models.DecimalField(decimal_places=10, default=1000, max_digits=19),
        ),
        migrations.AddField(
            model_name="fundraise",
            name="nft_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundraise",
            name="nft_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundraise",
            name="nft_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
